### ISSUE TITLE
 ADD ability to suspend currently active tab

### ISSUE THREAD

**Issue by allanlaal** [rNeomy/auto-tab-discard#105]
I heard a rumour somwhere that Firefox's native suspend mechanism does not the availability to suspend the currently active tab, but maybe you could build sth on top of it to lessen the CPU/RAM cost of each active tab destined for suspend :)

**Comment by rNeomy** [comment]
As you have already mentioned, it is not doable by the API.

> you could build sth on top

This is going to be messed up since you need to replace the actual page with an internal page and if for any reason your browser crashes it is going to remove all those replaced local pages. Maybe you can combine this extension with another extension but configure that extension to only act on active tabs.

**Comment by Luckz** [comment]
> The Great Suspender on Chrome made a greyed out screenshot of the webpage and replaced that inside the tab. only when you clicked the massive Refresh button in the center of that image, would it reload the tab (with forms filled as much as they were before "suspending")

Unfortunately this is also a great way to lose data, since tabs are replaced by information that relies on the specific extension.

**Comment by allanlaal** [comment]
I would be happy if there would even be a feature called:
"suspend" current tab, but loose all data
