### ISSUE TITLE
Option to undiscard all other tabs

### ISSUE THREAD

**Issue by dmlemos** [rNeomy/auto-tab-discard#115]
Request to add an option to undiscard all other tabs.

**Comment by rNeomy** [comment]
unfortunately, it is not doable. There is no API for that. The only possible way to remove discarding is to focus the tab

**Comment by allanlaal** [comment]
was about to suggest the same thing

how do Reload All tabs plugins work then?

**Comment by Luckz** [comment]
> was about to suggest the same thing
> 
> how do Reload All tabs plugins work then?

There is no API method for it: https://developer.chrome.com/extensions/tabs
There is discarding, and marking tabs to not be auto-discarded by the browser, but none to undiscard.

I suppose you would have to, for each window, activate (one at a time) the discarded tabs to make them load. And then set the original tab active again.
What's better, the API does not expose which tabs are unloaded because they haven't been clicked yet as discarded. You can only check for tabs that were discarded while the browser ran, while you have no distinction between tabs that weren't even loaded at all and tabs that were & are.
