### ISSUE TITLE
tabs are discarded regardless of settings

### ISSUE THREAD

**Issue by void-witch** [rNeomy/auto-tab-discard#209]
i have the "do not discard tabs playing media" option enabled, and tabs playing media are discarded. tabs are discarded even after setting "do not discard tab for this session", or adding the host to the exceptions list

currently, it seems like all tabs are discarded according to the default settings, regardless of any changes i make

**Comment by grahamperrin** [comment]
Which other extensions are enabled? 

Is the issue reproducible with Auto Tab Discard alone enabled?

Which version of Firefox, which platform?

### Here

Auto Tab Discard `0.4.1.1` with pre-release Firefox `86.0` on FreeBSD `14.0-CURRENT`. Exceptions: 

`brighton.ac.uk, old.reddit.com, www.diigo.com, servicedesk.brighton.ac.uk, remote.brighton.ac.uk, staffmail.brighton.ac.uk, chat.mozilla.org, app.element.io, forbetterscience.com, staff.brighton.ac.uk, unibrightonac.sharepoint.com, blogs.brighton.ac.uk, jobs.brighton.ac.uk, unicardcentral.brighton.ac.uk, print.brighton.ac.uk, github.com`

If I recall correctly, I found my Diigo and GitHub tabs unexpectedly discarded immediately after updating to `0.4.1.1`. 

Just once. Since then, nothing unexpected. 

Currently enabled add-ons: https://pastebin.com/raw/69bfXmDX

**Comment by void-witch** [comment]
awesome rss, betterttv, clearurls, colorzilla, deadname remover, disable ctrl-q and cmd-q, disable javascript, facebook container, google container, greasemonkey, https everywhere, impulse blocker, keepass tusk, link cleaner, nitter redirect, panorama tag groups, privacy badfer, sponsorblock, stylus, tomato clock, twitch chat pronouns, ublock origin, wallabagger

i can't test disabling all other extensions in any way except using a private window, and it seems that auto tab discard just doesn't work at all in a private window for me

firefox 85.0.1 on fedora 33

**Comment by grahamperrin** [comment]
Use **about:profiles** to create then launch a new profile; test Auto Tab Discard in this profile. Thanks.

**Comment by void-witch** [comment]
that's extremely handy, thank you!

it also seems that the issue no longer triggers after disabling and re-enabling the extension (both in a new profile, and my normal one). however, the extension also doesn't discard tabs automatically for me at all now

**Comment by void-witch** [comment]
it's started discarding tabs again, and respecting the exceptions list. maybe my firefox install is borked or a restart fixed it? either way, i'm gonna close the issue. thanks for the help!
