### ISSUE TITLE
Opening multiple tabs

### ISSUE THREAD

**Issue by hethhhhh** [rNeomy/auto-tab-discard#21]
When I'm restoring multiple tabs from bookmarks and using the option for 6 active tabs only, they still load. How can I prevent this?

**Comment by rNeomy** [comment]
Thanks for the report. In the dev version, it works as expected. Just note that the extension needs to wait for the dom elements to fully load before dispatching the discarding event, otherwise the loading icon remains although the tabs are already discarded. So it is not like we can ask to open in the discarded mode initially.
