### ISSUE TITLE
discarded tabs unread status

### ISSUE THREAD

**Issue by Sada-Mio** [rNeomy/auto-tab-discard#233]
Status of discarded tabs are now "unread" is this an intentional change in Version 0.4.7?

**Comment by rNeomy** [comment]
> Status of discarded tabs are now "unread"

Where? No this extension just uses the built-in API to perform discarding.

**Comment by Sada-Mio** [comment]
I use TreeStyleTab with a CSS profile that colors the tab "red" if it is  "unread" state.

With Auto-tab-discard v0.4.7 discarded tabs turns "red", but rolling back to v0.4.6 discarded tabs are not "red"

**Comment by rNeomy** [comment]
The new "v0.4.7" prepends a `Zzz` to the title of discarded tabs instead of graying out the favicons. Seems like TST finds a new title without the page being visited and considers this as a new unread tab. So you have two options

1. Ask ATD not to prepend this `Zzz` indicator.
2. Use the following CSS to change the color

```css
tab-item:not(.discarded).unread .label-content {
  color: red;
}
```

**Comment by Sada-Mio** [comment]
1. Removed the new "💤"  prepend in ATD options. Don't need this as I already have TST change tab opacity for discarded tabs. Everything works again like it did in  0.4.6, thanks the help.

2. Changing CSS to 
```
tab-item:not(.discarded).unread .label-content {
  color: red;
}
```
0.4.7 will make **all** discarded tabs not be "red". Still want to see which tabs are unread even after discarded.
