### ISSUE TITLE
Keep tabs unsuspended while navigating

### ISSUE THREAD

**Issue by sushinger** [rNeomy/auto-tab-discard#59]
As soon as I go to a suspended tab it will relaod it's original content.
I'd prefer it to remain suspended until I click on the screen or hit "return", just like it was possible with it's predeccessor "Tab Suspender (memrory saver)".

Any chance to bringe this feature back?

**Comment by rayman89** [comment]
Suspending a tab and doing what that addon does/did is different. That addon used a workaround and loaded a moz extension page to replace the actual tab and that extension tab had the order to redirect you to the page you were before. This addon actually suspends a tab which offers more memory saving benefits as well as the option to keep stuff associated with the tab that would be lost of you were to leave that url address. Also using the workaround means that the addon had to remember all those replaced tabs and that saved data could become corrupted and you would loose all those tabs. Also you can bookmark suspended tabs normally but if you were to bookmark the workaround tabs you would need to have the addon installed to reach the original url otherwise opening that bookmark will just give you an error.

**Comment by rNeomy** [comment]
as @rayman89 explained it is out of this extension's control. Unless browsers decide to allow focusing of discarded tabs, it would be not doable on the extension level

**Comment by Luckz** [comment]
As a workaround you can use the bindable extension shortcuts to navigate through the tab bar, and the bindable close tab button to close a tab without navigating to another discarded one.
