### ISSUE TITLE
Multiple tab support FF62+

### ISSUE THREAD

**Issue by rayman89** [rNeomy/auto-tab-discard#61]
Firefox 62+ includes the functionality to select multiple tabs using control or shift keys and do actions to all of those tabs. Could you rename "discard this tab" to "discard this tab(s)" and if more than one tab is selected unload all the selected tabs?

**Comment by rNeomy** [comment]
Nice! 

I don't see the info of the selected tabs in the API's callback; https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/onClicked

**Comment by rNeomy** [comment]
The one that we are interested in is [https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/onClicked](onClicked) listener which is fired when the user selects the extension's context menu item. The issue is there is no indication of other selected tabs except the active one in the returned object. 

Have you seen any other add-on that uses this multi-selection feature somehow?

**Comment by rayman89** [comment]
Multiple tab handler does it but they also use a menu with a list of tabs so IDK if they do it directly or trough the menu https://addons.mozilla.org/en-US/firefox/addon/multiple-tab-handler/

**Comment by rNeomy** [comment]
Thanks for the feature request. The force discarding item will discard all the highlighted tabs in the active window as of the next release.
