### ISSUE TITLE
Memory usage does not improve after discarding tabs in Firefox

### ISSUE THREAD

**Issue by ranolfi** [rNeomy/auto-tab-discard#79]
I have Firefox 65.0.1 with the standard settings and no other addons. Tested: open 10 windows, 15 tabs each for a total of 150 tabs. _auto-tab-discard_ with the default options discards tabs as expected, but my memory usage does not ever go down. I even tried manually discarding all but the active tab, and tried the `Minimize memory usage` command from `about:memory`, to no avail.

As it stands, it doesn't appear to make a difference having this extension enabled or not.

This is on Windows 10 x64 build 1803 as well as Arch Linux with Cinnamon 4.0.9.

Did the extension actually improved memory usage at some point?

Thanks.

**Comment by AeliusSaionji** [comment]
This addon just uses native calls to unload the tabs- the impact of this is entirely up to firefox. Nothing this extension can do to influence what firefox does with its memory.

Firefox 67 will natively support tab unloading in low memory conditions (https://www.ghacks.net/2019/03/01/firefox-67-automatically-unload-unused-tabs-to-improve-memory/) so presumably then firefox's memory management will be optimized for tab-unloading.

However, I suspect that there's actually nothing wrong with firefox's current handling of tab unloading. Unused RAM is wasted RAM- it does not really make sense to _clear_ the memory used by an unloaded tab, which is what you're expecting firefox should be doing.

As long as the memory taken up by unloaded tabs is marked unimportant, that memory will be overwritten _by the operating system_ **only when it is necessary** to make room for other applications.

You should repeat your test with these steps:

1. Open many tabs. Note firefox's memory usage
2. Fill up any unused memory with random programs (or in linux, just start putting files in /tmp).
3. Unload tabs in firefox
4. Watch Firefox's memory usage decrease.

Here, I've tested it myself with only 19 tabs. Windows started reclaiming memory from Firefox readily at 90% consumed memory.

19 tabs open:
![image](https://user-images.githubusercontent.com/4342746/53904102-4e13fd80-4013-11e9-9531-6b0d8d0a1960.png)

18 tabs unloaded:
![image](https://user-images.githubusercontent.com/4342746/53904116-5409de80-4013-11e9-8389-0974c6f925ad.png)

**Comment by ranolfi** [comment]
Hi @AeliusSaionji , thanks for the reply.

> This addon just uses native calls to unload the tabs- the impact of this is entirely up to firefox. Nothing this extension can do to influence what firefox does with its memory.

I know (at least I know better now). I also went ahead and tested with Chromium, where the discarded tabs release memory as I was expecting<sup>[1]</sup>. Perhaps I should have done that first and asked about the memory behavior on Firefox' Bugzilla instead of opening this issue for clarification. I considered contributing to Firefox and you say

> Firefox 67 will natively support tab unloading in low memory conditions (https://www.ghacks.net/2019/03/01/firefox-67-automatically-unload-unused-tabs-to-improve-memory/) so presumably then firefox's memory management will be optimized for tab-unloading.

I skimmed through the Bugzilla thread and it sounds good.

> However, I suspect that there's actually nothing wrong with firefox's current handling of tab unloading. Unused RAM is wasted RAM- it does not really make sense to _clear_ the memory used by an unloaded tab, which is what you're expecting firefox should be doing.
> 
> As long as the memory taken up by unloaded tabs is marked unimportant, that memory will be overwritten _by the operating system_ **only when it is necessary** to make room for other applications. Now you have the best of both worlds- the tab can be quickly retrieved but it is not consuming CPU, and the memory can be claimed by the operating system should that become necessary.

I agree with the principle that unused RAM is wasted RAM, nonetheless, in my scenario I am constantly running out of memory and at times I am unable to start virtual machines because of not enough RAM available. That forces me to terminate Firefox and browse anonymously or with Chromium. I did the test you suggested but in my case there was no observable difference, unfortunately.

Thanks again.

<br>
<sup>[1]</sup>: Btw, I noticed that discarded tabs are reloaded over the wire in the case of Chrome, but not in Firefox; I would hope Chrome would cache pages to disk instead of requesting them again.

**Comment by jbolton-corvalgroup** [comment]
> That forces me to terminate Firefox and browse anonymously or with Chromium.

@ranolfi  what do you mean by "browse anonymously? 

> Running out of memory

How long has it been since you re-launched firefox?

Task Manager is misleading. There's a bunch of ways to measure memory, it only shows one by default. It will even show memory is "used" even though it has been moved to the pagefile.

For comparison, the extension seems to be working for me. I currently have (I know I have a problem)

- open tabs: 1,247
- open windows: 149

But I never go higher than 7 GB usage. (Previously to this addon, I've seen it reach 10 GB) . My system RAM is 16 GB, so if you have less, I'd expect the cap to be far lower.

>  I am unable to start virtual machines because of not enough RAM available.

1. How much memory does your Task Manager report?
2. Is there anything other than firefox taking memory?
3. How much system RAM do you have?
4. How much are you allocating for the VM ? (VMs, compared to containers, use a *lot* of memory)

This might clear up things: [superuser.com/Windows says RAM ran out while there is still 4 GB of physical memory available](https://superuser.com/a/943185)

**Comment by ranolfi** [comment]
> 
> @ranolfi what do you mean by "browse anonymously?

I mean private browsing.

> 
> How long has it been since you re-launched firefox?

No longer than two and a half hours.

> Task Manager is misleading. There's a bunch of ways to measure memory, it only shows one by default. It will even show memory is "used" even though it has been moved to the pagefile.
> 

I know. My main system is Linux, though, and I monitor private, shared and resident memory (and also the swap).

> For comparison, the extension seems to be working for me. I currently have (I know I have a problem)
> 
>     * open tabs: 1,247
> 
>     * open windows: 149
> 

Ah, that's impressive. I came close to that once or twice, but with 8 GiB physical memory total, it's harder.

> 
>     1. How much memory does your Task Manager report?
> 
>     2. Is there anything other than firefox taking memory?

It is Firefox, I'm positive about it. Closing Firefox will reclaim 5GiB of RAM or more.

> 
>     3. How much system RAM do you have?

8 GiB.

> 
>     4. How much are you allocating for the VM ? (VMs, compared to containers, use a _lot_ of memory)
> 

2536 MiB + 128 MiB for the virtual graphics adapter.

I should say that, having conducted more tests, I did see a difference of up to  15% - 20% less memory usage when tabs are discarded with this addon. So it *is* in fact working. It's just not immediate though. RAM is reclaimed up to a minute after all tabs are discarded. Tested with Firefox 66.0.5.

I'm now on FF 67.0 and it hasn't got any better btw.

Thank you for your comments. I guess this issue can be closed.

**Comment by jbolton-corvalgroup** [comment]
# max RAM usage in (obsolete?) config settings ?

> 5GiB of RAM [...] I came close to that once or twice, but with 8GiB physical memory total, it's harder.

I don't know if this is still true, but if you didn't have a RAM max limit set it used to use a percentage of RAM. That would make sense with the numbers you, and I have .

This sounded promising: about:config: [browser.cache.memory.capacity, and browser.cache.memory.enable ](http://kb.mozillazine.org/About:config_Entries) 

But those don't seem to even exist in my Settings. Have you noticed if they work after creating the values? The wiki says **last updated 2017**.

# current RAM configs? 

I searched for other variables in config. Most memory values seem to  be about number of items, but not the actual total RAM. **I wanted to set mine to cap ~5 GB.**

Yesterday I was having performance issues running a game. I had *just* loaded firefox. Maybe if I had waited to my config using 5 minutes , maybe it would have been fine ? I do have an exceptionally high window and tab count -- so maybe that's my actual problem.

# native tab discard functions

If I understand, some of the not freeing RAM on discarded tabs might be an issue in firefox's codebase, so voting here might help?: https://github.com/rNeomy/auto-tab-discard/issues/88

> > @ranolfi what do you mean by "browse anonymously?

> I mean private browsing.

I was asking when you said anonymous because (some) people don't know it's not anonymizing themself. Because history is still logged by router logs, the website itself, and possibly anyone else between you and the website / ISP. [It's mainly about preventing caches, passwords, local history](https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history) As-in someone locally using your profile.

> No longer than two and a half hours.

That sounds fine. If it's weeks, then it might help.

> I guess this issue can be closed

I think both you and the developer have permissions to close, because you're the author.

**Comment by charlesroddie** [comment]
> @AeliusSaionji Unused RAM is wasted RAM- it does not really make sense to clear the memory used by an unloaded tab, which is what you're expecting firefox should be doing.

I would expect firefox do do this too. It's a problem because Windows Task manager reports firefox as using the memory. Firefox appears to be malfunctioning in using multiple GB of RAM 100% of the time. Therefore it can't be diagnosed when it is really malfunctioning and when it not "really" using the RAM it/Windows claims it is using. Also if another app needs that memory, it may not be reclaimable instantly.

@ranolfi Currently I am trying Firemin 6 (in conjunction with Auto-Tab-Discard) and Firefox's memory usage went down from 4GB to 30MB! However if I set it memory reclamation 60s then Firefox's memory usage goes from 30MB to 1GB+ even while doing nothing before being cut back.

> @jbolton-corvalgroup some of the not freeing RAM on discarded tabs might be an issue in firefox's codebase, so voting here might help?

I loaded all links from that list and don't see anything related.

**Comment by ninmonkey** [comment]
I'm extremely skeptical that any modern browser in-use will only use 30 MB RAM total. If you look in the app directory, the dll's alone are more than 100 MB. (For comparison, the `firefox.exe` itself is `0.57 KB`.) 

` Firemin`'s website says he is calling some windows API to cleanup memory, **multiple times a second** -- which might be why it could display that.  This sounds like apps that are common on phones. They make the numbers look good, ie. low RAM usage, but, often actually make hardware have to work harder. If you can find out which API calls he's using, it'd be easier to know for sure.

Check out the settings in auto-tab-discard. There's toggles to prevent tabs from freeing, which is useful depending on the site.

**Comment by ranolfi** [comment]
@charlesroddie: That looks interesting. Too bad it targets Windows only and I'm not using Windows a lot these days.

**Comment by AeliusSaionji** [comment]
I'm still not convinced that anything is wrong. So far we have only the supposition that maybe the browser will not relinquish memory when it should.

If that's true, that's an actual bug in the browser. Without a demonstration of this happening, I'm not sure why we're assuming that it is happening.

**Comment by ranolfi** [comment]
It's a bug in the browser indeed. I found some reports that might be relevant. Will investigate further when I can find the time.

**Comment by arpit9295** [comment]
As of Firefox 78.0.2 (64-bit), this is still an issue,

**Comment by grahamperrin** [comment]
Works for me; not an issue with the extension. 

Tested with e.g. https://app.element.io/#/room/#freenode_#freebsd:matrix.org/$1607378617315840FuqVN:matrix.org

Before discarding: 

![image](https://user-images.githubusercontent.com/192271/101442426-3d449a00-3913-11eb-9328-51eae1dc3023.png)

– and soon after discarding: 

![image](https://user-images.githubusercontent.com/192271/101442465-51889700-3913-11eb-978e-c01b3eaca7df.png)

– VIRT for PID `86291` dropped from 10.0G to 3,919M. 

```text
grahamperrin@mowa219-gjp4-8570p:~ % pkg query '%o %v %R' firefox
www/firefox 83.0_4,2 FreeBSD
grahamperrin@mowa219-gjp4-8570p:~ % date ; uname -v
Tue  8 Dec 2020 05:07:59 GMT
FreeBSD 13.0-CURRENT #72 r367936: Sun Nov 22 21:46:00 GMT 2020     root@mowa219-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
```
YMMV; for tabs with less demanding content, the gains from discarding will be less dramatic (or negligible). 

### If you find no effect from discarding tabs

Best to seek explanations in Mozilla/Firefox support areas.

**Comment by ranolfi** [comment]
@grahamperrin, I'm afraid what matters in this case is resident memory (RES), isn't it? Other than that, yeah, nothing that can be fixed within this extension.

**Comment by grahamperrin** [comment]
> resident memory (RES)

This also dropped, albeit less dramatically – from 1,354M to 1,264M.

Whether uses of VIRT have a significant impact on overall performance of the computer will depend on a variety of factors. 

Utilities such as [bpytop](https://github.com/aristocratos/bpytop) and [bashtop](https://github.com/aristocratos/bashtop) can offer overviews of disk activity (and more) but for me, with FreeBSD-CURRENT – and the bottleneck of a notebook hard disk drive – amongst the most useful utilities is: 

* [gstat(8)](https://www.freebsd.org/cgi/man.cgi?query=gstat&sektion=8&manpath=FreeBSD+12.2-RELEASE)

– if there's anything like thrashing, it'll appear in red: 

![image](https://user-images.githubusercontent.com/192271/102747638-81468e80-4358-11eb-8bd3-0079709f1ab4.png)

![image](https://user-images.githubusercontent.com/192271/102747869-fdd96d00-4358-11eb-9614-4a5bb9fe836f.png)

----

… all of which is pleasantly off topic :-) from this issue, which is not reproducible: 

* memory usage _does_ improve

– not an issue with the extension. I suggest closure.

**Comment by ranolfi** [comment]
Yeah, in any case I'm closing since there's nothing that can be done to further improve resident memory consumption extension-wise. Further progress to be pursued in Firefox codebase.

Thanks for your comments :)
