### ISSUE TITLE
Discarded tab "forgets" its URL/page

### ISSUE THREAD

**Issue by campbellkerr** [rNeomy/auto-tab-discard#95]
- Issue seems to be random/intermittent
- Have seen it happen on home PC, work PC and in FF Nightly 

Occasionally, when selecting a discarded tab, the URL is missing/forgotten. The favicon still shows up, but the tab is undiscarded and treated as a New Tab. GIF below shows an Australia Post (red 'P' favicon) that has been discarded but can no longer be loaded/used, but other discarded tabs work fine:

![autotabiscard](https://user-images.githubusercontent.com/38451588/58755422-1855b680-8527-11e9-8086-79eff537929d.gif)

**Comment by ninmonkey** [comment]
# Solution:

- close tab `ctrl+w`
- re-open `ctrl+shift+t

# When I have a tab that's "blank", it

- has no title
- might not have favicon
- no history. Meaning back, forward, and refesh -- none of them work.
- It seems to happen on session loading when you start firefox back up. I **think** it might only happen to the focused tab of a window. 

If I do this, I don't actually "lose" any tabs. 

IIRC this is actually a problem with Firefox discarding code -- not this addon.

I'm not using Treestyle. It could be a factor too.

**Comment by kernc** [comment]
A wholly unsubstantiated conjecture, but since [Firefox issue 1397667 "_a tab discarded immediately after creation gains a corrupted session state_"](https://bugzilla.mozilla.org/show_bug.cgi?id=1397667) had been long since fixed, could it not be that the "temporary fix for #24" (https://github.com/rNeomy/auto-tab-discard/commit/7836ef1cd936fb62ea927d44b91e31638e760bc0), i.e.:
https://github.com/rNeomy/auto-tab-discard/blob/b9702abb68d9d20649dbc61286a77614ed5a885f/background.js#L435-L452
is the culprit here?

And while reviewing https://github.com/rNeomy/auto-tab-discard/commit/7836ef1cd936fb62ea927d44b91e31638e760bc0, it's _not a good idea_ to base actions on error messages:
https://github.com/rNeomy/auto-tab-discard/blob/b9702abb68d9d20649dbc61286a77614ed5a885f/background.js#L444
For this particular message @Rob--W in [Firefox issue 1397667](https://bugzilla.mozilla.org/show_bug.cgi?id=1397667#c6) said:

> warning: internal changes are coming, so the error message might change within a couple of Firefox releases

This, so far, appears [not to have been the case](https://github.com/search?q=repo%3Amozilla%2Fgecko-dev+%22No+matching+message+handler%22&type=code), but relying on:
```js
lastError.result === MessageChannel.RESULT_NO_HANDLER
```
looks like a safer option.

**Comment by rNeomy** [comment]
Should be fixed by the next major release, if not please reopen
